### ISSUE TITLE
DiGraph has not attribute `_succ`

### ISSUE THREAD

**Issue by dilawar** [networkx/networkx#2909]
This is very odd. It working on ubuntu-16.04 with python3. However on openSUSE Tumbleweed and Arch Linux, I am getting the following error:

```
 File "./schedule_aws.py", line 128, in main
    schedule_aws( )
  File "./schedule_aws.py", line 120, in schedule_aws
    reformat( )
  File "./schedule_aws.py", line 39, in reformat
    speakers = g_.successors( 'source' )
  File "/usr/lib/python3.6/site-packages/networkx/classes/digraph.py", line 779, in successors
    return iter(self._succ[n])
AttributeError: 'DiGraph' object has no attribute '_succ'
```

Version:

```
python3 -c 'import networkx;print(networkx.__version__)'
2.0
```

**Comment by dilawar** [comment]
My mistake. The graph was pickled by different python version and loaded into different python version.
