### ISSUE TITLE
'NoneType' object has no attribute 'get' from greedy_modularity_communities() in v2.6.2

### ISSUE THREAD

**Issue by bramson** [networkx/networkx#5026]
I have an undirected, weighted network and I am trying to run greedy_modularity_communities() on it.  This morning I had NetworkX v2.5 and it worked great with 'weight=None' or one of my edgeWeights , but I couldn't use the resolution parameter.  So, I updated my networkx, and now when I run the algorithm, I get a TypeError in a weird place no matter what the parameters are.

### Current Behavior
```
  File "...\networkMeasureScoring_v3.py", line 1511, in <module>
    communitiesModularity = list(community.greedy_modularity_communities(thisNetwork, weight=edgeWeight, resolution=thisGamma))

  File "...\networkx\algorithms\community\modularity_max.py", line 93, in greedy_modularity_communities
    dq_dict = {

  File "...\networkx\algorithms\community\modularity_max.py", line 94, in <dictcomp>
    i: {

  File "...\networkx\algorithms\community\modularity_max.py", line 95, in <dictcomp>
    j: 2 * q0 * G.get_edge_data(i, j).get(weight, 1.0)

AttributeError: 'NoneType' object has no attribute 'get'
```

### Expected Behavior

I expect it to output a list of lists of nodes, like it did under v2.5.
When I run the example from the documentation it works:
```
from networkx.algorithms.community import greedy_modularity_communities
G = nx.karate_club_graph()
c = list(greedy_modularity_communities(G))
print(sorted(c[0]))
```
So, presumably it's due to some feature of my network, but... without changing the network, this worked with networkX v2.5, but fails in v2.6

### Steps to Reproduce
Run 
`communitiesModularity = list(community.greedy_modularity_communities(thisNetwork, weight=edgeWeight, resolution=thisGamma))`
on some thisNetwork for any edgeWeight and any thisGamma.

Actually, I get the same error nor running just 
`communitiesModularity = list(community.greedy_modularity_communities(thisNetwork))`
on my network, so it has nothing to do with the weight or resolution parameters

My interpretation is that either G doesn't have the edge (i,j) at this point.
It shouldn't fail to get edge data of any edge (i,j) that should be in the input graph (by construction).
I mean, all the i and j elements are pulled from G, so, how could it not exist?
Could it have been removed from G during the modularity maximization processes.
Would that happen if i doesn't have any neighbors?
I've isolated the largest component of my network, so initially all nodes have at least one neighbor.

### Environment

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
NetworkX version: 2.6.2

### Additional context

Like I said, it shouldn't matter, but the network is a road network extracted from Open Street Map.

**Comment by z3y50n** [comment]
Hello, I think this bug was solved by #4965 and it is not yet included in the latest stable `networkx` release.

**Comment by bramson** [comment]
I see.  Well, it's good news that the bug had been previously found and solved, but it's still the case that I can't use it at the moment.  Is there an ETA for the next stable release?  Is there a reasonable way to run the corrected version until then?

**Comment by MridulS** [comment]
>  Is there a reasonable way to run the corrected version until then?

You can install the main branch which has the changes by using pip: 
```
pip install git+https://github.com/networkx/networkx.git
```

Feel free to reopen this issue if the error persists.

**Comment by bramson** [comment]
Okay, I'll see if I can do something through conda and check if the new version works.

**Comment by bramson** [comment]
I installed the main branch, and it was able to run the unweighted version.

When specifying an edge weight (which are integers from 0 to 1000) it crashes with the following error:
```
  File "...\networkx\algorithms\community\modularity_max.py", line 218, in greedy_modularity_communities
    dq_heap[row].remove(d_old)

  File "...\networkx\utils\mapped_queue.py", line 114, in remove
    pos = self.d[elt]

KeyError: (-3.7296259711422466e-06, 116087, 116086)
```

> Feel free to reopen this issue if the error persists.

I don't know how to reopen the issue.

**Comment by dschult** [comment]
Now you are running into another bug identified in #5000 and #4992
We have an idea how to fix that bug, but it is not yet implemented in the codebase.   Ack....

**Comment by dschult** [comment]
We are thinking of making a 2.6.3 release once we get the bugs sorted out.

**Comment by bramson** [comment]
I see.  At least it's a known bug.  
I know these are things that you can't exactly plan for, but do you have an expected/hoped release date for the release with these fixes?  
If it's within a week or so, I can work on other things while waiting.
If it's expected to take a while, then I'll need to make another strategy on this research thread.

**Comment by dschult** [comment]
It will not be within a week. I am hoping for a fix within two weeks and a release within a month.

In the meantime, as a solution a short term fix. The floating point round-off issue (that results in a KeyError) should be fixed by scaling all edge weights in the graph by the total weight of all edges in the graph.  The floating point round-off error comes from dividing (in the formula) by (2*m) where m is the total weight of all edges in the graph.  If you can multiply all your edge weights by m (or even 2*m just to be safe, but division by 2 should not introduce much round-off error), then the values in the numerator should cancel those in the denominator. I'm not sure that this will always work because there may be some round-off before the cancelation. But I think it should work.  Your edge weights are all integers, m will be an integer. Definitely worth a try.  Can you test that with the case that gave you this most recent error?  If that doesn't work, I'll try to get a code fix posted in this issue that could replace that function.

**Comment by dschult** [comment]
You could also download/copy/paste the solution in #5000 where @tristanic rounds the values to ensure the keys are the same when they are close.  If that function works for you please let me know.

**Comment by bramson** [comment]
I multiplied the weights by the sum of edge weights and the algorithm doesn't crash.  Thank you!
