### ISSUE TITLE
Sphinx inconsistent in including source code in documentation: e.g., Graph.edges() & DiGraph.edges()

### ISSUE THREAD

**Issue by michaelpacer** [networkx/networkx#1857]
The ability to immediately see the source code when reading documentation is extremely helpful. An example of where this is straightforward can be found at 

https://networkx.github.io/documentation/latest/reference/generated/networkx.Graph.edges.html#networkx.Graph.edges

which links to: 

https://networkx.github.io/documentation/latest/_modules/networkx/classes/graph.html#Graph.edges

However, this is not a feature that is consistently available throughout the documentation despite the documentation being auto-built using sphinx. For example,

https://networkx.github.io/documentation/latest/reference/generated/networkx.DiGraph.edges.html#networkx.DiGraph.edges

has no link to a representation of the source code. There _is_ code in the documentation for the [`DiGraph` class](https://networkx.github.io/documentation/latest/_modules/networkx/classes/digraph.html), and a link from the top level class to the source in the documentation. However, if you look for the analogous `edges` method under the `DiGraph` class, it doesn't exist! 

Of course the method (`edges`) in both the `Graph` and `DiGraph` classes exists, and the docstrings are fairly extensive in both of them. But for some reason sphinx did not include this when the docs are built. I figured that the [autoclass and automethod calls](https://github.com/networkx/networkx/blob/master/doc/rst_templates/autosummary/class.rst) were building the classes documentation for both `DiGraph` and `Graph`, but then it makes no sense why it would successfully include `edges()` in one case and exclude them in the other. I also can't find anything that explicitly excludes `edges()` in the DiGraph case, so I'm a bit at a loss.

Sidenote: I was going to try to build the documents to see if I could figure out what was going on and commit a fix if I could…but in attempting to get my fork & local in a state that is consistent with the current master branch I have gotten into a spiral of git confusion where my local repo says its consistent both with this repo (`upstream`) and my fork (`origin`) but github says that my fork is ahead by commits that seem to be included in this repo! So all the time I was going to devote to trying to fix that instead went into this whirlpool of gittitude trying to arrive at some kind of a consistent state. Was there some kind of history rewriting that went on in the past couple of months? If so, could you put a note warning that this occurred and instructions on how to avoid these kinds of issues (even if it's just suggesting to people that they nuke their repo and start over).

**Comment by SanketDG** [comment]
Hi, it looks like you will somehow your fork pulled things from `v1.11` branch. I looked at your fork and it looks like if you reset back 15 commits,your upstream fork should be all right.

**Comment by michaelpacer** [comment]
Hmm, it seems like those commits were included at some point in the master branch (I hadn't done any merges from other branches into master) so they must have been removed? Regardless — ok with sourcetree's and your help I figured that out. 

Now I'm running into different issues, where the make gh-pages script is failing with error:

    atlas.py  FAIL: ('requires pygraphviz ', 'http://networkx.lanl.gov/pygraphviz ', '(not available for Python3)')

which is odd, since I made sure I'm using `2.7.10`

I think it might have to do with an issue with `pygraphviz` (`pip` installing that leaves me with a `clang` error) I'll update when I know more. I think there might be a dependency somewhere on `graphviz` that isn't being automatically installed? If so I don't know why `networkx` works if it's an actual dependency…oh well. Further down the rabbit hole we go :)

**Comment by michaelpacer** [comment]
Ok, above is fixed. A bit of a confusing error message (oh well). 

Now when I try to build the docs I run into the following error (which seems to be more closely related to the actual `networkx` code:

    degree_histogram.py Traceback (most recent call last):
      File "make_gallery.py", line 62, in <module>
    execfile(example)
      File "degree_histogram.py", line 11, in <module>
        degree_sequence=sorted([d for n,d in G.degree()],reverse=True) # degree sequence
    TypeError: 'int' object is not iterable
    make: *** [build/generate-stamp] Error 1

Seems like this should be causing a problem when anyone tries to use `degree_histogram`?

**Comment by dschult** [comment]
Strange... the degree_histogram example is working on reathedocs.org and on my machine without an error.

**Comment by dschult** [comment]
I do get that error if I import networkx 1.8 instead of the latest.  
Are you sure you got the dev version loading?

**Comment by michaelpacer** [comment]
From inside the usual python2 interpreter:
    >>> import networkx
    >>> networkx.__version__
    '2.0.dev_20150923175606'

Also, I was trying to run `make gh-pages` from within the `doc` directory
and I had jumped through all of those hoops to make sure I was up to date
with the `upstream/master` branch, so I don't know how I could have even
had access to `nx` version 1.8.

Sidenote: I wasn't running the `make gh-pages` command after importing but
just inside the directory itself in the command line. As far as I knew,
`make` is usually run from the command line and you import things into a
python interpreter and therefore there's no meaning to importing to the
command line. But I readily acknowledge that I could be totally mistaken.
What set of commands did you use to build the docs? Why did you need to
import networkx at all to build them? I might be doing this incorrectly,
and would love to know how to do it better (or at least to know if there
are multiple ways available for building docs). Thanks!

**Comment by michaelpacer** [comment]
From inside the usual `python2` interpreter:

    >>> import networkx
    >>> networkx.__version__
    '2.0.dev_20150923175606'

Also, I was trying to run `make gh-pages` from within the `doc` directory and I had jumped through all of those hoops to make sure I was up to date with the `upstream/master` branch, so I don't know how I could have even had access to `nx` version 1.8.

Sidenote: I wasn't running the `make gh-pages` command after importing but just inside the directory itself in the command line. As far as I knew, `make` is usually run from the command line and you import things into a python interpreter and therefore there's no meaning to importing to the command line. But I readily acknowledge that I could be totally mistaken. What set of commands did you use to build the docs? Why did you need to import networkx at all to build them? I might be doing this incorrectly, and would love to know how to do it better (or at least to know if there are multiple ways available for building docs). Thanks!

**Comment by michaelpacer** [comment]
Also realized that there was this inconsistency in the docs as well, in the [docstring for the DiGraph class found in the official version of the docs](https://networkx.github.io/documentation/development/_modules/networkx/classes/digraph.html) the copyright is:

```
#    Copyright (C) 2004-2011 by
#    Aric Hagberg <hagberg@lanl.gov>
#    Dan Schult <dschult@colgate.edu>
#    Pieter Swart <swart@lanl.gov>
#    All rights reserved.
#    BSD license.
```

Whereas in the current docstring for the `DiGraph` class in the actual repo the copyright statement is:

```
#    Copyright (C) 2004-2015 by
#    Aric Hagberg <hagberg@lanl.gov>
#    Dan Schult <dschult@colgate.edu>
#    Pieter Swart <swart@lanl.gov>
#    All rights reserved.
#    BSD license.
```

So I think it must be that the source code parts of the documentation are no longer being built from the source itself, but are simply left over from some previous time when the docs were built.

I am guessing that someone who knows more about the history of the project might be able to figure out exactly when these pages stopped being built (would seem to be at some point in 2011) and if we can identify the date when that change occurred it might be possible to update all of these pages by resurrecting the code that was altered (which would be comparatively easier than trying to reëngineer the docs to include the source code from scratch).

**Comment by dschult** [comment]
>
> Also, I was trying to run `make gh-pages` from within the `doc` directory
> and I had jumped through all of those hoops to make sure I was up to date
> with the `upstream/master` branch, so I don't know how I could have even
> had access to `nx` version 1.8.
>


> Sidenote: I wasn't running the `make gh-pages` command after importing but
> just inside the directory itself in the command line. As far as I knew,
> `make` is usually run from the command line and you import things into a
> python interpreter and therefore there's no meaning to importing to the
> command line. But I readily acknowledge that I could be totally mistaken.
> What set of commands did you use to build the docs? Why did you need to
> import networkx at all to build them? I might be doing this incorrectly,
> and would love to know how to do it better (or at least to know if there
> are multiple ways available for building docs). Thanks!
>
Yes, the make command is run from the command line. It then runs commands
like sphinx to create the docs based on files in the docs directory as well
as information from the python objects created when sphinx runs python and
imports networkx.

Given that your "by hand" import of networkx provides the development
version, it might be that you have some old files in your doc directory. To
try a fresh build, you can cd to the doc directory and try

    python -c "import networkx;print networkx.__version__"
    make clean
    make gh-pages

hope this helps...
Dan

**Comment by michaelpacer** [comment]
So running 

```
python -c "import networkx; print(networkx.__version__)"
```
gave me `1.9.1`, which is surprising (since I thought i'd installed from the trunk w/ `pip3 install -e .`). That said, it doesn't require going all the way back to `1.8` to find this problem. 

I checked and it's because I forgot to actually use the upgrade flag (`pip3 install -e . -U`). 

Doing `make clean` and `make gh-pages` didn't affect the result prior to the upgrade, and the docs are building now that I've upgraded the system python's `networkx` to the dev build.

Unfortunately, though the doc string's copyright is now up-to-date, when I try to go to the DiGraph source as reported in the documentation it still has the originally posted issues (at least it does at   http://localhost:8000/html/_modules/networkx/classes/digraph.html#DiGraph, which will be a nonfunctioning link unless you open a server from inside the `networkx/doc/build/` directory (e.g., with `python3 -m http.server`)). That is, there is no inclusion of the documentation from `DiGraph.edges()` whereas there is inclusion of edges under `Graph.edges()` at the analogous site (also requiring a server from inside the `doc/build` directory) http://localhost:8000/html/_modules/networkx/classes/graph.html#Graph.edges. 

I've got no idea why this happens, but at least I've now verified that it's a problem with the current `sphinx` build and not just an out-of-date version of the docs online.

**Comment by michaelpacer** [comment]
Also — I just noticed that the `gh-pages.py` script failed with this traceback:

```
Traceback (most recent call last):
  File "gh-pages.py", line 124, in <module>
    branch = re.match('\# On branch (.*)$', status).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
make: *** [gh-pages] Error 1
```

But since I had cleaned the sphinx build before attempting `make gh-pages` again, and it says on the documents that they were built today (Nov 23 2015) I'm fairly confident that it did build successfully, but just ran into issues re the `gh-pages` script.

**Comment by dschult** [comment]
Everything looks OK at [readthedocs](https://networkx.readthedocs.org/en/latest/reference/generated/networkx.DiGraph.edges.html#networkx.DiGraph.edges)

Not that it helps you much except to know that it can work.  For readthedocs we use the sphinx 1.3.1 from github and NOT the sphinx 1.3.1 from pip.  The newer version has a few commits that fix autosummary, and while I don't know whether they do anything for links to course codes, maybe there is a fix in those commits there too.

So that's another potential source of trouble--the version of sphinx should be the stable release 1.3.1 from github and not the 1.3.1 from pip.

Maybe it'd be good to revisit the goal here... I understand the source link is not working on latest or on the [v1.10 docs](https://networkx.github.io/documentation/latest/reference/generated/networkx.DiGraph.edges.html) at networkx.github.io.  At networkx.readthedocs.org I believe they are working for the [latest docs](https://networkx.readthedocs.org/en/latest/reference/generated/networkx.DiGraph.edges.html) but not for the [v1.10 docs](https://networkx.readthedocs.org/en/networkx-1.10/reference/generated/networkx.DiGraph.edges.html).

Would you agree? Do you see other problems that need fixing regarding this issue (other than some documentation on how to create the documentation. :)

**Comment by dschult** [comment]
The viewcode extension to sphinx puts links to the source code in the documentation.  Unfortunately the links are only added to methods that are not inherited from another class. So, when ```DiGraph``` inherits a method from ```Graph```, that method has no link to the source from the ```DiGraph``` documentation.

I've created an issue at sphinx-dox/sphinx#2196 but in the meantime I don't see a fix for this issue.

**Comment by hagberg** [comment]
Closed for now.  Will resolve itself when sphinx issue is fixed.
